### PR TITLE
Add support for connection strings.

### PR DESCRIPTION
**Pull request by arjovanramshorst**
I Liked this package but needed support for connection strings, so I've made a small change to the db collection parser so it also accepts connection strings. 

usage:
`node variety-cli.js <connectionString>/<collection> <options>`

Should have no impact on existing workflows, validation is probably a bit less strict though. If you think it's a good addition to variety, let me know and I'll improve the PR, otherwise feel free to do with it what you like ;)

### CODE REVIEW

**Comment by JamesCropcho** [comment]
Thank you for your contribution, Arjo.

@todvora et al: do you have any thoughts on this?


James

**Comment by todvora** [comment]
Looks good, let's merge it and release a new version of the package.

**Comment by JamesCropcho** [comment]
I have squash-merged and I will release a new version of the package soon.

On behalf of all of the users of Variety, thank very much, Arjo. We are grateful for your contribution.


James

**Comment by arjovanramshorst** [comment]
Any idea when you're going to release a new package including this change? Then I can remove my fork and clean up the project I'm working on by just using the official variety-cli package again. Thanks in advance :+1:

**Comment by JamesCropcho** [comment]
Good to hear from you, Arjo. Don't thank me if I haven't done anything!

I'm sorry to hear we're jamming you up from our end. Unless Tomáš (@todvora) gets to it first, I should be able to release the package some time this month. I'll keep you posted.


―James

**Comment by JamesCropcho** [comment]
Hey Tomáš (@todvora), I created a new release at https://github.com/variety/variety-cli/releases/tag/v0.5.0. However, I suspect I lack the permissioning to register the release at https://www.npmjs.com/package/variety-cli.

Unless I am mistaken (let me know), could you kindly do so?


―James

**Comment by todvora** [comment]
Hello everyone, I just published the 0.5.0 release: https://www.npmjs.com/package/variety-cli/v/0.5.0

Thanks @arjovanramshorst for your contribution and @JamesCropcho for managing the whole task!

Best regards,
Tomas

**Pull request merged**
